### PR TITLE
add support influxdb2 (#311)Co-authored-by: Franck Nijhof <git@frenck.dev>

### PR DESCRIPTION
**Pull request by kamontat**
# Proposed Changes

Add configuration options+change influxdb service script to support Glances writing to an InfluxDB 2.x database.

Only different is this will export data to only single influxdb
and the config syntax I copied from [home assistant influxdb integration](https://www.home-assistant.io/integrations/influxdb/)

## Related Issues

hassio-addons/addon-glances#217

### CODE REVIEW

**Comment by kamontat** [comment]
@frenck Please help me review this.

**Comment by kamontat** [comment]
PR is failed because I cannot add label to this pull-request.

**Comment by frenck** [comment]
have patience please.

**Comment by kamontat** [comment]
Please don't close it yet.

**Review by frenck — DISMISSED** [review]
Looks good, thanks @kamontat 👍

**Pull request merged**
